name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics1:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_habits: yes
          plugin_people: yes
          plugin_people_types: followers
          
  github-metrics2:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_anilist: yes
          plugin_anilist_user: yanfd
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 3
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_playlist: https://embed.music.apple.com/cn/playlist/replay-2023/pl.rp-2ZZGIvDowlg0?l=en-GB
          plugin_music_limit: 5
          
          
          
          
          
          
